export const sampleMealPlan = {
  weekStart: '2026-03-23',
  days: [
    {
      date: '2026-03-23',
      day: 'Monday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R003',
          recipeName: 'Egg omelette + chapati',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 egg + 1 small chapati (22g carb)',
            adults: 'Standard',
            kids: 'Plain omelette, mild',
          },
          pickyModifier: 'Plain omelette, paratha with jam, banana',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R019',
          recipeName: 'Apple + roasted chana',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 apple + 1/2 cup chana',
            adults: 'Standard',
            kids: 'Apple slices only',
          },
          pickyModifier: 'Apple slices with peanut butter',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R018',
          recipeName: 'Chicken curry + roti',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 roti + curry, no rice',
            adults: '2 roti + curry',
            kids: 'Mild curry + extra roti',
          },
          pickyModifier: 'Mild gravy, no whole spices',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-24',
      day: 'Tuesday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R016',
          recipeName: 'Protein oats',
          cookScaledFor: 3,
          portions: {
            muhtasim: '3 tbsp oats + 1 boiled egg',
            adults: 'Standard bowl',
            kids: 'Oats with banana',
          },
          pickyModifier: 'Banana and honey version',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R020',
          recipeName: 'Yogurt + cucumber raita',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup yogurt',
            adults: 'Standard',
            kids: 'Yogurt with banana',
          },
          pickyModifier: 'Serve plain yogurt separately',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R001',
          recipeName: 'Vegetable dal khichuri',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 cup khichuri',
            adults: '1.5 cups',
            kids: 'Plain khichuri + fried egg',
          },
          pickyModifier: 'Less spice, smoother texture',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-25',
      day: 'Wednesday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R017',
          recipeName: 'Chira upma with egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup chira + egg',
            adults: 'Standard bowl',
            kids: 'Plain chira + milk',
          },
          pickyModifier: 'Plain chira with sugar and milk',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R019',
          recipeName: 'Apple + roasted chana',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 apple + 1/2 cup chana',
            adults: 'Standard',
            kids: 'Apple slices only',
          },
          pickyModifier: 'Apple slices with peanut butter',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R002',
          recipeName: 'Grilled fish + stir-fry veggies',
          cookScaledFor: 3,
          portions: {
            muhtasim: 'Fish + vegetables, no rice',
            adults: 'Fish + vegetables',
            kids: 'Fish fingers + plain rice',
          },
          pickyModifier: 'Fish fingers version',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-26',
      day: 'Thursday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R003',
          recipeName: 'Egg omelette + chapati',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 egg + 1 small chapati',
            adults: 'Standard',
            kids: 'Plain omelette, mild',
          },
          pickyModifier: 'Plain omelette, paratha with jam',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R020',
          recipeName: 'Yogurt + cucumber raita',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup yogurt',
            adults: 'Standard',
            kids: 'Yogurt with fruit',
          },
          pickyModifier: 'Serve plain yogurt separately',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R001',
          recipeName: 'Vegetable dal khichuri',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 cup khichuri',
            adults: '1.5 cups',
            kids: 'Plain khichuri + fried egg',
          },
          pickyModifier: 'Less spice, smoother texture',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-27',
      day: 'Friday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R016',
          recipeName: 'Protein oats',
          cookScaledFor: 3,
          portions: {
            muhtasim: '3 tbsp oats + 1 boiled egg',
            adults: 'Standard bowl',
            kids: 'Oats with banana',
          },
          pickyModifier: 'Banana and honey version',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R019',
          recipeName: 'Apple + roasted chana',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 apple + 1/2 cup chana',
            adults: 'Standard',
            kids: 'Apple slices only',
          },
          pickyModifier: 'Apple slices with peanut butter',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R018',
          recipeName: 'Chicken curry + roti',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 roti + curry, no rice',
            adults: '2 roti + curry',
            kids: 'Mild curry + extra roti',
          },
          pickyModifier: 'Mild gravy, no whole spices',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-28',
      day: 'Saturday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R017',
          recipeName: 'Chira upma with egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup chira + egg',
            adults: 'Standard bowl',
            kids: 'Plain chira + milk',
          },
          pickyModifier: 'Plain chira with sugar and milk',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R020',
          recipeName: 'Yogurt + cucumber raita',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup yogurt',
            adults: 'Standard',
            kids: 'Yogurt with fruit',
          },
          pickyModifier: 'Serve plain yogurt separately',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R002',
          recipeName: 'Grilled fish + stir-fry veggies',
          cookScaledFor: 3,
          portions: {
            muhtasim: 'Fish + vegetables, no rice',
            adults: 'Fish + vegetables',
            kids: 'Fish fingers + plain rice',
          },
          pickyModifier: 'Fish fingers version',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
    {
      date: '2026-03-29',
      day: 'Sunday',
      meals: [
        {
          slot: 'Breakfast',
          recipeId: 'R003',
          recipeName: 'Egg omelette + chapati',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 egg + 1 small chapati',
            adults: 'Standard',
            kids: 'Plain omelette, mild',
          },
          pickyModifier: 'Plain omelette, paratha with jam',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Lunch',
          recipeId: 'R015',
          recipeName: 'Dal + rice + mixed veg + egg',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1/2 cup rice + dal + egg',
            adults: 'Standard',
            kids: 'Plain dal-bhaat + egg',
          },
          pickyModifier: 'Plain dal-bhaat, no spicy sabji',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Snack',
          recipeId: 'R019',
          recipeName: 'Apple + roasted chana',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 apple + 1/2 cup chana',
            adults: 'Standard',
            kids: 'Apple slices only',
          },
          pickyModifier: 'Apple slices with peanut butter',
          kitchenNotes: '',
          assignedCook: 'Cook A',
        },
        {
          slot: 'Dinner',
          recipeId: 'R001',
          recipeName: 'Vegetable dal khichuri',
          cookScaledFor: 3,
          portions: {
            muhtasim: '1 cup khichuri',
            adults: '1.5 cups',
            kids: 'Plain khichuri + fried egg',
          },
          pickyModifier: 'Less spice, smoother texture',
          kitchenNotes: '',
          assignedCook: 'Cook A + B',
        },
      ],
    },
  ],
}

export const sampleShopping = {
  total: 12,
  checked: 3,
  progress: 25,
  categories: {
    Protein: [
      {
        row: 2,
        ingredient: 'Chicken breast (skinless)',
        category: 'Protein',
        quantity: '450 g',
        unit: 'g',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
      {
        row: 3,
        ingredient: 'Egg',
        category: 'Protein',
        quantity: '18 whole',
        unit: 'whole',
        tag: 'Weekly',
        checked: true,
        shopper: 'Shopper A',
        notes: '',
      },
      {
        row: 4,
        ingredient: 'Rui fish (rohu)',
        category: 'Protein',
        quantity: '600 g',
        unit: 'g',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
    ],
    Vegetables: [
      {
        row: 5,
        ingredient: 'Mixed veg',
        category: 'Vegetables',
        quantity: '6 cups',
        unit: 'cup',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
      {
        row: 6,
        ingredient: 'Onion',
        category: 'Vegetables',
        quantity: '8 medium',
        unit: 'medium',
        tag: 'Weekly',
        checked: false,
        shopper: 'Shopper A',
        notes: '',
      },
      {
        row: 7,
        ingredient: 'Tomato',
        category: 'Vegetables',
        quantity: '8 medium',
        unit: 'medium',
        tag: 'Weekly',
        checked: true,
        shopper: 'Shopper A',
        notes: '',
      },
      {
        row: 8,
        ingredient: 'Cucumber',
        category: 'Vegetables',
        quantity: '4 medium',
        unit: 'medium',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
    ],
    'Grains & Dal': [
      {
        row: 9,
        ingredient: 'Brown rice',
        category: 'Grains & Dal',
        quantity: '4 cups',
        unit: 'cup',
        tag: 'Weekly',
        checked: true,
        shopper: 'Shopper A',
        notes: '',
      },
      {
        row: 10,
        ingredient: 'Red lentil dal',
        category: 'Grains & Dal',
        quantity: '3 cups',
        unit: 'cup',
        tag: 'Weekly',
        checked: false,
        shopper: 'Shopper A',
        notes: '',
      },
      {
        row: 11,
        ingredient: 'Whole wheat flour',
        category: 'Grains & Dal',
        quantity: '1.5 kg',
        unit: 'kg',
        tag: 'Weekly',
        checked: false,
        shopper: 'Shopper A',
        notes: '',
      },
    ],
    Fruits: [
      {
        row: 12,
        ingredient: 'Apple',
        category: 'Fruits',
        quantity: '7 whole',
        unit: 'whole',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
      {
        row: 13,
        ingredient: 'Banana',
        category: 'Fruits',
        quantity: '10 whole',
        unit: 'whole',
        tag: 'Daily',
        checked: false,
        shopper: 'Shopper B',
        notes: '',
      },
    ],
  },
}

export const sampleRecipes = {
  count: 9,
  recipes: [
    {
      id: 'R001',
      name: 'Vegetable dal khichuri',
      category: 'Dinner',
      cuisine: 'Bangladeshi',
      prepTime: 10,
      cookTime: 25,
      difficulty: 'Easy',
      tags: ['diabetic-safe', 'nafld-friendly'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 320,
      carbs: 38,
      protein: 14,
      fat: 8,
      fiber: 9,
      baseServings: 1,
      ingredients: [
        { key: 'brown_rice', qty: 0.25, unit: 'cup' },
        { key: 'moong_dal', qty: 0.25, unit: 'cup' },
        { key: 'cauliflower', qty: 0.5, unit: 'cup' },
        { key: 'carrot', qty: 0.5, unit: 'cup' },
      ],
      method: '1. Soak rice and dal. 2. Pressure cook with vegetables. 3. Finish with a light tarka.',
      pickyModifier: 'Serve plain, less spice, add fried egg if needed',
      notes: 'One-pot meal.',
    },
    {
      id: 'R002',
      name: 'Grilled fish + stir-fry veggies',
      category: 'Dinner',
      cuisine: 'Bangladeshi',
      prepTime: 15,
      cookTime: 15,
      difficulty: 'Easy',
      tags: ['diabetic-safe', 'low-carb'],
      season: 'all',
      kidFriendly: false,
      pickyOk: false,
      calories: 290,
      carbs: 12,
      protein: 28,
      fat: 10,
      fiber: 5,
      baseServings: 1,
      ingredients: [
        { key: 'rui_fish', qty: 150, unit: 'g' },
        { key: 'broccoli', qty: 1, unit: 'cup' },
        { key: 'bell_pepper', qty: 0.5, unit: 'cup' },
      ],
      method: '1. Marinate fish. 2. Pan-sear. 3. Stir-fry vegetables. 4. Serve.',
      pickyModifier: 'Make fish fingers for kids',
      notes: 'Good low-carb dinner.',
    },
    {
      id: 'R003',
      name: 'Egg omelette + chapati',
      category: 'Breakfast',
      cuisine: 'Bangladeshi',
      prepTime: 5,
      cookTime: 10,
      difficulty: 'Easy',
      tags: ['diabetic-safe'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 280,
      carbs: 22,
      protein: 16,
      fat: 10,
      fiber: 3,
      baseServings: 1,
      ingredients: [
        { key: 'egg', qty: 2, unit: 'whole' },
        { key: 'onion', qty: 2, unit: 'tbsp' },
        { key: 'tomato', qty: 2, unit: 'tbsp' },
        { key: 'whole_wheat_flour', qty: 30, unit: 'g' },
      ],
      method: '1. Whisk eggs with chopped vegetables. 2. Cook the omelette. 3. Make chapati and serve.',
      pickyModifier: 'Keep one omelette plain and skip chili',
      notes: 'Fast weekday breakfast.',
    },
    {
      id: 'R015',
      name: 'Dal + rice + mixed veg + egg',
      category: 'Lunch',
      cuisine: 'Bangladeshi',
      prepTime: 10,
      cookTime: 30,
      difficulty: 'Easy',
      tags: ['diabetic-safe', 'everyday'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 410,
      carbs: 48,
      protein: 22,
      fat: 9,
      fiber: 8,
      baseServings: 1,
      ingredients: [
        { key: 'red_lentil_dal', qty: 0.5, unit: 'cup' },
        { key: 'brown_rice', qty: 0.5, unit: 'cup' },
        { key: 'mixed_veg', qty: 2, unit: 'cup' },
        { key: 'egg', qty: 1, unit: 'whole' },
      ],
      method: '1. Cook dal. 2. Cook rice. 3. Stir-fry vegetables. 4. Boil or fry egg. 5. Plate.',
      pickyModifier: 'Keep one plate plain with no spicy sabji',
      notes: 'Reliable lunch template.',
    },
    {
      id: 'R016',
      name: 'Protein oats',
      category: 'Breakfast',
      cuisine: 'Bangladeshi',
      prepTime: 5,
      cookTime: 7,
      difficulty: 'Easy',
      tags: ['quick', 'diabetic-safe'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 260,
      carbs: 28,
      protein: 14,
      fat: 8,
      fiber: 5,
      baseServings: 1,
      ingredients: [
        { key: 'oats', qty: 0.5, unit: 'cup' },
        { key: 'milk', qty: 0.75, unit: 'cup' },
        { key: 'egg', qty: 1, unit: 'whole' },
      ],
      method: '1. Cook oats in milk. 2. Add boiled egg on the side.',
      pickyModifier: 'Use banana and a little honey for kids',
      notes: 'Very fast breakfast.',
    },
    {
      id: 'R017',
      name: 'Chira upma with egg',
      category: 'Breakfast',
      cuisine: 'Bangladeshi',
      prepTime: 8,
      cookTime: 10,
      difficulty: 'Easy',
      tags: ['quick'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 300,
      carbs: 34,
      protein: 12,
      fat: 10,
      fiber: 4,
      baseServings: 1,
      ingredients: [
        { key: 'flattened_rice', qty: 0.75, unit: 'cup' },
        { key: 'egg', qty: 1, unit: 'whole' },
        { key: 'onion', qty: 2, unit: 'tbsp' },
      ],
      method: '1. Soften chira. 2. Saute onion. 3. Toss with chira and egg.',
      pickyModifier: 'Serve plain chira with milk for kids',
      notes: 'Flexible breakfast.',
    },
    {
      id: 'R018',
      name: 'Chicken curry + roti',
      category: 'Dinner',
      cuisine: 'Bangladeshi',
      prepTime: 15,
      cookTime: 35,
      difficulty: 'Medium',
      tags: ['diabetic-safe'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 380,
      carbs: 30,
      protein: 32,
      fat: 11,
      fiber: 5,
      baseServings: 1,
      ingredients: [
        { key: 'chicken_breast', qty: 150, unit: 'g' },
        { key: 'onion', qty: 1, unit: 'medium' },
        { key: 'tomato', qty: 1, unit: 'medium' },
        { key: 'whole_wheat_flour', qty: 40, unit: 'g' },
      ],
      method: '1. Build the curry base. 2. Cook chicken. 3. Make roti and serve.',
      pickyModifier: 'Keep gravy mild and skip whole spices',
      notes: 'Core family dinner.',
    },
    {
      id: 'R019',
      name: 'Apple + roasted chana',
      category: 'Snack',
      cuisine: 'Bangladeshi',
      prepTime: 2,
      cookTime: 0,
      difficulty: 'Easy',
      tags: ['quick', 'portable'],
      season: 'all',
      kidFriendly: true,
      pickyOk: true,
      calories: 180,
      carbs: 24,
      protein: 6,
      fat: 3,
      fiber: 6,
      baseServings: 1,
      ingredients: [
        { key: 'apple', qty: 1, unit: 'whole' },
        { key: 'roasted_chana', qty: 0.5, unit: 'cup' },
      ],
      method: '1. Slice apple. 2. Serve with roasted chana.',
      pickyModifier: 'Serve apple only if needed',
      notes: 'Simple afternoon snack.',
    },
    {
      id: 'R020',
      name: 'Yogurt + cucumber raita',
      category: 'Snack',
      cuisine: 'Bangladeshi',
      prepTime: 5,
      cookTime: 0,
      difficulty: 'Easy',
      tags: ['cooling', 'summer'],
      season: 'summer',
      kidFriendly: true,
      pickyOk: true,
      calories: 120,
      carbs: 10,
      protein: 6,
      fat: 4,
      fiber: 1,
      baseServings: 1,
      ingredients: [
        { key: 'yogurt', qty: 0.5, unit: 'cup' },
        { key: 'cucumber', qty: 0.5, unit: 'cup' },
      ],
      method: '1. Mix yogurt and chopped cucumber. 2. Season lightly and serve chilled.',
      pickyModifier: 'Serve plain yogurt separately',
      notes: 'Good cooling snack.',
    },
  ],
}

export const sampleKitchenDay = {
  date: '2026-03-23',
  day: 'Monday',
  peopleToFeed: 3,
  mealsToday: 4,
  timeline: [
    {
      prepTime: '6:00 AM',
      serveTime: '6:30 AM',
      slot: 'Breakfast',
      recipe: 'Egg omelette + chapati',
      recipeId: 'R003',
      scaledFor: 3,
      assignedCook: 'Cook A',
      portions: {
        muhtasim: '1 egg + 1 chapati',
        adults: 'Standard',
        kids: 'Plain omelette',
      },
      pickyModifier: 'Plain omelette, paratha with jam',
      kitchenNotes: '',
    },
    {
      prepTime: '10:00 AM',
      slot: 'Shopping',
      recipe: 'Daily market run',
      assignedCook: 'Shopper B',
      kitchenNotes: 'Buy fresh chicken, cucumber, tomato, and yogurt',
    },
    {
      prepTime: '11:30 AM',
      serveTime: '1:00 PM',
      slot: 'Lunch',
      recipe: 'Dal + rice + mixed veg + egg',
      recipeId: 'R015',
      scaledFor: 3,
      assignedCook: 'Cook A',
      portions: {
        muhtasim: '1/2 cup rice + dal + egg',
        adults: 'Standard',
        kids: 'Plain dal-bhaat + egg',
      },
      pickyModifier: 'Plain dal-bhaat, no spicy sabji',
      kitchenNotes: '',
    },
    {
      prepTime: '4:30 PM',
      serveTime: '5:00 PM',
      slot: 'Snack',
      recipe: 'Apple + roasted chana',
      recipeId: 'R019',
      scaledFor: 3,
      assignedCook: 'Cook A',
      pickyModifier: 'Apple slices with peanut butter',
      kitchenNotes: '',
    },
    {
      prepTime: '7:30 PM',
      serveTime: '9:30 PM',
      slot: 'Dinner',
      recipe: 'Chicken curry + roti',
      recipeId: 'R018',
      scaledFor: 3,
      assignedCook: 'Cook A + B',
      portions: {
        muhtasim: '1 roti + curry, no rice',
        adults: '2 roti + curry',
        kids: 'Mild curry + extra roti',
      },
      pickyModifier: 'Mild gravy, no whole spices',
      kitchenNotes: 'Keep one portion very mild.',
    },
  ],
  pickyAlerts: ['Bone-in chicken', 'Spicy gravy', 'Mixed vegetables with visible chunks'],
}

export const sampleNextWeekPlan = null
